### ISSUE TITLE
Implementar componente de persistencia

### ISSUE THREAD

**Issue by silasiebert** [silasiebert/rss-news-manager#3]
### Objetivo
Criar um modulo de persistencia, que use sqlite #2 . 
### Justificativa
O software 1 e o software 2 presizam armazenar e recuperar dados do banco.

**Comment by gabrielnaoto** [comment]
needs validation, but closing issue.

**Comment by silasiebert** [comment]
@gabrielnaoto Sobre a noticia preciso de data de publicação e o site em que foi publicado.
Também preciso de um metodo no newsDao que retorne a ultima noticia salva do site pasado por parametro.

**Comment by gabrielnaoto** [comment]
Beleza, vou fazer.

**Comment by gabrielnaoto** [comment]
Feito. Re-abrir em casos de mudanças.
