### ISSUE TITLE
Implementar biblioteca de RSS

### ISSUE THREAD

**Issue by silasiebert** [silasiebert/rss-news-manager#4]
### Objetivo
É preciso ler os feeds RSS dos sites de noticia cadastrados.
### Justificativa
Recuperar de maneira simples as noticias.

**Comment by silasiebert** [comment]
@gabrielnaoto Alguma sugestao na hora de pegar as noticias para evitar pegar niticias repetidas?
edit: ver #3

**Comment by gabrielnaoto** [comment]
Fiz alterações na tarefa #3. Elas devem te auxiliar a resolver este problema. Agora você tem um método na interface NewsDAO que te permite recuperar a última notícia de um determinado feed (precisa do id do feed para consultar) e cada notícia contém informações de qual feed ela pertence e qual foi sua data de publicação. @silasiebert confirme se isso ajuda.
